spring.application.name=BackEnd
spring.datasource.url=jdbc:mysql://db:3306/appdb
spring.datasource.username=app
spring.datasource.password=app

logging.level.org.hibernate.tool.schema.override=ERROR
logging.level.org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl=ERROR
spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY

#esto es para pruebas, crea la bbdd y luego la destruye, esta bien para pruebas
#ya que el import.sql se va a iniciar cada vez y nos daria error
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect