--Inserts de usuarios
INSERT INTO users (username, password_hash, role, created_at) VALUES ('admin', '$2a$10$8.UnVuG9HHgffUDAlk8q6OuVGkqCYAdVqKz3T.Y6B5V7Bw.T.Y6B5', 'ROLE_ADMIN', '2024-01-01 10:00:00');
INSERT INTO users (username, password_hash, role, created_at) VALUES ('jdoe', '$2a$10$vI8BvWZpC8ZpX9.Z7H6O.uM8vI8BvWZpC8ZpX9.Z7H6O.uM8vI8B', 'ROLE_USER', '2024-01-15 14:30:00');
INSERT INTO users (username, password_hash, role, created_at) VALUES ('mgarcia', '$2a$10$L2k.XyZ1.234567890abcdL2k.XyZ1.234567890abcdL2k.XyZ', 'ROLE_USER', '2024-02-01 09:15:00');
INSERT INTO users (username, password_hash, role, created_at) VALUES ('moderator_01', '$2a$10$PqR.StU1.vWxYz2.345678PqR.StU1.vWxYz2.345678PqR.St', 'ROLE_MODERATOR', '2024-02-05 18:45:00');
INSERT INTO users (username, password_hash, role, created_at) VALUES ('guest_user', '$2a$10$AbC.DeF1.gHiJkL3.456789AbC.DeF1.gHiJkL3.456789AbC.De', 'ROLE_GUEST', CURRENT_TIMESTAMP);
--Inserts de clientes
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('12345678A', 'Juan Pérez', '600111222', 'juan.perez@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('23456789B', 'María García', '600222333', 'maria.garcia@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('34567890C', 'Carlos Rodríguez', '600333444', 'carlos.rod@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('45678901D', 'Ana Martínez', '600444555', 'ana.mtz@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('56789012E', 'Luis López', '600555666', 'luis.lopez@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('67890123F', 'Elena Sánchez', '600666777', 'elena.sanchez@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('78901234G', 'Javier Gómez', '600777888', 'javier.gomez@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('89012345H', 'Lucía Díaz', '600888999', 'lucia.diaz@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('90123456I', 'Diego Torres', '600999000', 'diego.torres@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('01234567J', 'Marta Ruiz', '611111222', 'marta.ruiz@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('11223344K', 'Sergio Hernández', '611222333', 'sergio.h@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('22334455L', 'Paula Jiménez', '611333444', 'paula.j@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('33445566M', 'Andrés Moreno', '611444555', 'andres.moreno@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('44556677N', 'Sara Muñoz', '611555666', 'sara.munoz@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('55667788Ñ', 'Fernando Romero', '611666777', 'fer.romero@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('66778899O', 'Raquel Alonso', '611777888', 'raquel.alonso@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('77889900P', 'Ricardo Navarro', '611888999', 'ricardo.nav@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('88990011Q', 'Silvia Ramos', '611999000', 'silvia.ramos@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('99001122R', 'Alberto Castro', '622111222', 'alberto.castro@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('00112233S', 'Irene Ortega', '622222333', 'irene.ortega@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('12345678A', 'Juan Pérez', '600111222', 'juan.perez@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('23456789B', 'María García', '600222333', 'maria.garcia@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('34567890C', 'Carlos Rodríguez', '600333444', 'carlos.rod@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('45678901D', 'Ana Martínez', '600444555', 'ana.mtz@email.com');
INSERT INTO clients (dni, nombre, telefono, correo) VALUES ('56789012E', 'Luis López', '600555666', 'luis.lopez@email.com');

--Inserts de habitaciones de prueba
-- PLANTA 1: INDIVIDUALES (101-140)
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (101, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (102, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (103, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (104, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (105, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (106, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (107, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (108, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (109, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (110, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (111, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (112, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (113, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (114, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (115, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (116, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (117, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (118, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (119, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (120, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (121, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (122, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (123, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (124, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (125, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (126, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (127, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (128, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (129, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (130, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (131, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (132, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (133, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (134, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (135, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (136, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (137, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (138, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (139, 'Individual', 'Disponible', 45.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (140, 'Individual', 'Disponible', 45.0);

-- PLANTA 2: DOBLES (201-240)
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (201, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (202, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (203, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (204, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (205, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (206, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (207, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (208, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (209, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (210, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (211, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (212, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (213, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (214, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (215, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (216, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (217, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (218, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (219, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (220, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (221, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (222, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (223, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (224, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (225, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (226, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (227, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (228, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (229, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (230, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (231, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (232, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (233, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (234, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (235, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (236, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (237, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (238, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (239, 'Doble', 'Disponible', 75.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (240, 'Doble', 'Disponible', 75.0);

-- PLANTA 3: SUITES (301-320)
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (301, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (302, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (303, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (304, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (305, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (306, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (307, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (308, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (309, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (310, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (311, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (312, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (313, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (314, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (315, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (316, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (317, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (318, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (319, 'Suite', 'Disponible', 120.0);
INSERT INTO habitacion (numero, tipo, estado, precio_por_noche) VALUES (320, 'Suite', 'Disponible', 120.0);

--Inserts de actividades de prueba
INSERT INTO activities (descripcion, precio, fecha_comienzo, fecha_fin, max_participantes) VALUES ('Excursión en 4x4', 45.00, '2026-05-19 10:00:00', '2026-05-19 12:00:00', 10);
INSERT INTO activities (descripcion, precio, fecha_comienzo, fecha_fin, max_participantes) VALUES ('Kayak en la costa', 30.00, '2026-05-19 12:30:00', '2026-05-19 14:30:00', 8);
INSERT INTO activities (descripcion, precio, fecha_comienzo, fecha_fin, max_participantes) VALUES ('Ruta de senderismo', 20.00, '2026-05-19 15:00:00', '2026-05-19 17:00:00', 15);
INSERT INTO activities (descripcion, precio, fecha_comienzo, fecha_fin, max_participantes) VALUES ('Paseo en barco', 60.00, '2026-05-20 09:30:00', '2026-05-20 11:30:00', 12);
INSERT INTO activities (descripcion, precio, fecha_comienzo, fecha_fin, max_participantes) VALUES ('Buceo básico', 80.00, '2026-05-20 12:00:00', '2026-05-20 14:00:00', 6);

--Inserts tabla actividades-clientes
INSERT INTO activities_clients (activity_id, client_id) VALUES (1, 1);
INSERT INTO activities_clients (activity_id, client_id) VALUES (1, 2);
INSERT INTO activities_clients (activity_id, client_id) VALUES (2, 3);
INSERT INTO activities_clients (activity_id, client_id) VALUES (3, 4);
INSERT INTO activities_clients (activity_id, client_id) VALUES (3, 5);
INSERT INTO activities_clients (activity_id, client_id) VALUES (4, 1);
INSERT INTO activities_clients (activity_id, client_id) VALUES (4, 2);
INSERT INTO activities_clients (activity_id, client_id) VALUES (4, 3);
INSERT INTO activities_clients (activity_id, client_id) VALUES (4, 4);
INSERT INTO activities_clients (activity_id, client_id) VALUES (4, 5);
INSERT INTO activities_clients (activity_id, client_id) VALUES (5, 1);